imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@RestApiBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: fr

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~
    serializer:
        enabled: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form_themes:
        # other form themes
        - 'VichUploaderBundle:Form:fields.html.twig'

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

# FOSUser Configuration
fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: AppBundle\Entity\User
    # config send mail
    registration:
        confirmation:
            enabled: true
            from_email:
                address:        noreply@tickenet.fr
                sender_name:    WebMaster
        # surcharge des champs du formulaire
        form:
            type: AppBundle\Form\RegistrationType
    from_email:
        address:        noreply@tickenet.fr
        sender_name:    WebMaster
    resetting:
        email:
            from_email:
                address:        noreply@tickenet.fr
                sender_name:    WebMaster

# VICH Configuration
vich_uploader:
    db_driver: orm

    mappings:
            user_image:
                uri_prefix:         http://dev.mysh3ll.fr/TPResa_Symfony3-Git/web/uploads/user/images
                upload_destination: '%kernel.root_dir%/../web/uploads/user/images'
                namer:              vich_uploader.namer_uniqid
            event_image:
                uri_prefix:         http://dev.mysh3ll.fr/TPResa_Symfony3-Git/web/uploads/event/images
                upload_destination: '%kernel.root_dir%/../web/uploads/event/images'
                namer:              vich_uploader.namer_uniqid

# FOSJsRoutingBundle Configuration
fos_js_routing:
    routes_to_expose: [ admin_event_date_booked, admin_event_date_booked_year, admin_event_delete, admin_event_delete_booked, front_resa_panier_add, front_resa_booked_seat, admin_category_delete, admin_room_delete, front_search ]

# Knp Paginator Configuration
knp_paginator:
    page_range: 5                      # default page range used in pagination control
    default_options:
        page_name: page                # page query parameter name
        sort_field_name: sort          # sort field query parameter name
        sort_direction_name: direction # sort direction query parameter name
        distinct: true                 # ensure distinct results, useful when ORM queries are using GROUP BY statements
    template:
        pagination: KnpPaginatorBundle:Pagination:twitter_bootstrap_v3_pagination.html.twig     # sliding pagination controls template
        sortable: KnpPaginatorBundle:Pagination:sortable_link.html.twig # sort link template

# Knp Snappy Configuration
knp_snappy:
    pdf:
        enabled:    true
        binary:     /usr/local/bin/wkhtmltopdf
        options:
            no-outline: true
            page-size: LETTER
            # Recommended to set UTF-8 as default encoding :)
            encoding: UTF-8
    image:
        enabled:    true
        binary:     /usr/local/bin/wkhtmltoimage
        options:    []
    temporary_folder: %kernel.cache_dir%/snappy

# FOSRestBundle Configuration
fos_rest:
    routing_loader:
        include_format: false
    view:
        view_response_listener: true
    format_listener:
        rules:
            - { path: '^/api/', priorities: ['json'], fallback_format: 'json' }
            - { path: '^/', stop: true }

# lexik jwt bundle
lexik_jwt_authentication:
    private_key_path: '%jwt_private_key_path%'
    public_key_path:  '%jwt_public_key_path%'
    pass_phrase:      '%jwt_key_pass_phrase%'
    token_ttl:        '%jwt_token_ttl%'