app:
    resource: "@AppBundle/Controller/DefaultController.php"
    type:     annotation
backOffice:
    resource: "@AppBundle/Resources/config/routing/backOffice/routingBack.yml"
frontOffice:
    resource: "@AppBundle/Resources/config/routing/frontOffice/routingFront.yml"
FOSUserPages:
    resource: "@AppBundle/Resources/config/routing/routingFOSUserBundle.yml"
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
rest_api:
    resource: "@RestApiBundle/Controller/DefaultController.php"
    type:     annotation
    prefix:   /
users:
    type:     rest
    resource: RestApiBundle\Controller\UserController
    prefix: /api
ticket:
    type:     rest
    resource: RestApiBundle\Controller\TicketController
    prefix: /api
