# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    app.form.registration:
        class: AppBundle\Form\RegistrationType
        tags:
            - { name: form.type, alias: app_user_registration }

    # Event Listener
    kernel.listener.kernel_request:
       class: AppBundle\EventListener\ErrorRedirect
       arguments:
           router: "@router"
       tags:
           - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }

    # Twig Extension
    montant_ht.twig_extension:
        class: AppBundle\Twig\MontantHTExtension
        public: false
        tags:
            - { name: twig.extension }

    #Snappy PDF Generation
    snappy.pdf.ticket:
        class: AppBundle\Controller\frontOffice\user\PdfController
        arguments:
            container: "@service_container"

    # Force à détecter le Header Authorization pou Apache
    fix_authentication_header_listener:
        class: RestApiBundle\EventListener\AuthenticationHeaderListener
        tags:
        - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 255 }

    # Guard authentication
#    app.jwt_token_authenticator:
#        class: RestApiBundle\Security\JwtAuthenticator
##        arguments: ['@doctrine.orm.entity_manager', '@lexik_jwt_authentication.encoder']
#        autowire: true